### ISSUE TITLE
数据集链接打不开

### ISSUE THREAD

**Issue by qfnulixinmeng** [pairlab/v-cdn#1]
- 您给出的**球和衣物的数据**的下载链接在国内无法打开。

- 我尝试了很多种办法（如切换浏览器、翻墙）但仍然无法解决，能否请求您用一个其他的方式（如百度网盘链接）**提供数据集**呢？非常非常感谢！

**Comment by YunzhuLi** [comment]
Hi, thank you for your interest in our work! I have uploaded the data to Baidu Wangpan and included the links in the following section. Let me know if you still have problems accessing the data.
https://github.com/pairlab/v-cdn/blob/master/README.md#evaluation-using-pre-trained-models
